### ISSUE TITLE
More specific definition for online image URLs

### ISSUE THREAD

**Issue by sander** [iainc/Markdown-Content-Blocks#3]
Right now the spec says that an online image URL

> includes: • a period, followed by one of the following path extensions: `png` `jpg` `jpeg` `gif` `tif` `tiff`.

This definition matches for example the string `https://www.gifs.com`, which is clearly not an image URL.

I guess changing “includes” to “ends with” would be too restrictive: some valid image URLs might include query strings. How does iA Writer internally detect online image URLs?

**Comment by antons** [comment]
@sander You’re correct. The phrasing is wrong here. As you mention, the extension can be optionally followed by a query string, and the spec was mean to convey that. What do you think about this edit?

***

A <a id="online-image" href="#online-image">online image</a> URL consists of either:

- a sequence of zero or more characters between an opening `<` and a closing `>` that contains no spaces, line breaks, or unescaped `<` or `>` characters, or
- a nonempty sequence of characters that does not include ASCII space or control characters, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses that is not itself inside a balanced pair of unescaped parentheses

which ends with:

- a period, followed by one of the following path extensions: `png` `jpg` `jpeg` `gif` `tif` `tiff`.
- optionally followed by a query string.

iA Writer automatically uses direct links for images hosted on some services. Currently, it adds `raw=1` query item for online image URLs from GitHub and Dropbox.

**Comment by sander** [comment]
Looks good to me, thanks.
