### ISSUE TITLE
Base directory of local file path isn’t defined

### ISSUE THREAD

**Issue by odkr** [iainc/Markdown-Content-Blocks#6]
I'm using iA Writer together with Pandoc and have written a simple script to take care of file transclusion. While doing so, I found that there are some things you may want to clarify in the specs:

You use only relative paths in your examples, but to which directory are these paths relative? Suppose, I have three files: _root.markdown_, _dir/foo.markdown_, and _dir/subdir/bar.markdown_,  and I want to transclude _dir/subdir/bar.markdown_ in _dir/foo.markdown_ and _dir/foo.markdown_ in _root.markdown_. What would I say in _dir/foo.markdown_? That is, would I have to say ``/dir/subdir/bar.markdown`` or ``/subdir/bar.markdown``?

Also, may I give absolute paths? Like, presumably, so: ``//absolute/path.markdown``?

Don’t get me wrong, I can figure that out by trial and error, but, I find, this should be covered by the spec.

**Comment by antons** [comment]
Thank you for letting us know! We’ll update the spec to clarify this.

Paths are always relative to the folder where the document which includes a content blocks is located. There’s no way to specify an absolute path, because the absolute path would be different in different environments. For example, iCloud Drive on macOS and iOS have different file system locations.

```
root.markdown → /dir/foo.markdown
dir/foo.markdown → /subdir/bar.markdown
dir/subdir/bar.markdown
```

**Comment by dazzaji** [comment]
What if the next version of your spec clarified that a URL is an option for defining file paths? I've worked on a few projects that would have benefited greatly from a simple way to transclude MD files at a publicly accessible URL.  A URL provides a standard cross-boundary reference point and cite syntax and enables one to "get" the content in any number of ways. As a practical matter, this would be valuable for using standard and distributed legal content like required definitions or rules from statutes and regulations and expected clauses from standard contracts.  Even when all the files are at the same site, a URL can identify the location without using some irregular syntax for indicating files above the folder where the document which includes a content blocks is located.  Could you add URL as a an optional file path syntax?

**Comment by antons** [comment]
Thank you for the suggestion! We’ll keep it mind as we improve content blocks.
