### ISSUE TITLE
Licensing of the Languages.json file

### ISSUE THREAD

**Issue by Witiko** [iainc/Markdown-Content-Blocks#7]
Hello,

does the `Languages.json` file fall under the CC BY-SA license? I would like to [include the file in the witiko/markdown package](https://github.com/Witiko/markdown/issues/4). The package is LPPL-licensed, however, which violates the Share-Alike clause.

**Comment by onebigclownshoe** [comment]
It does. Based on the progress in the thread you linked, you've decided to build your own so I shall close this.
