### ISSUE TITLE
Disallow spaces in URLs

### ISSUE THREAD

**Issue by Crissov** [iainc/Markdown-Content-Blocks#9]
You currently have this example among others:

```
/Savings Account.csv 'Recent Transactions'
```

To enable future extensions, literal spaces should be disallowed in file paths, i.e. URLs.

```
/Savings%20Account.csv 'Recent Transactions'
```

I think it would be a bad idea to support any alternative escape syntax as found in shells and programming languages, e.g.:

```
/Savings\ Account.csv 'Recent Transactions'
/Savings\_Account.csv 'Recent Transactions'
/Savings_Account.csv 'Recent Transactions'
/Savings&#32;Account.csv 'Recent Transactions'
/Savings&#x20;Account.csv 'Recent Transactions'
(/Savings Account.csv) 'Recent Transactions'
"/Savings Account.csv" 'Recent Transactions'
```

**Comment by antons** [comment]
[John Gruber](https://daringfireball.net/projects/markdown/):
> The overriding design goal for Markdown’s formatting syntax is to make it as readable as possible.

Content blocks were created for Markdown. They are intentionally designed to allow spaces in file names.

**Comment by Crissov** [comment]
This is deliberately inconsistent with Commonmark's [`link-destination`](http://spec.commonmark.org/0.28/#link-destination) then. CM only allows these:

```
/Savings%20Account.csv 'Recent Transactions'
</Savings%20Account.csv> 'Recent Transactions'
```

> A **link destination** consists of either
>
> - a sequence of zero or more characters between an opening `<` and a closing `>` that contains no spaces, line breaks, or unescaped `<` or `>` characters, or
>
> - a nonempty sequence of characters that does not include ASCII space or control characters, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses. (Implementations may impose limits on parentheses nesting to avoid performance issues, but at least three levels of nesting should be supported.)

You could try to get spaces allowed inside angle brackets, but I believe this has been discussed and rejected for good reasons.

```
</Savings Account.csv> 'Recent Transactions'
```

**Comment by antons** [comment]
Yes, it is deliberately inconsistent. We believe that it results in a better writing and reading experience. 

The spec provides two separate definitions: “online image URL”, “local file path”. The latter mentions spaces:

> A <a id="local-file" href="#local-file">local file</a> path consists of one or more path components. Path component consists of:
>
> - a forward slash `/`;
> - followed by file name: a sequence of one or more characters including spaces (but not tabs);
> - followed by path extension (optional for all but last path component), which consists of a period, followed by a sequence one or more uppercase or lowercase ASCII characters or numbers.

Perhaps a “local file path” is not the best term. If you have an idea for a better name, let us know. Thank you for bringing this to our attention.
